backend:
  name: github
  repo: gowthamtekion/ds-demo
  branch: master


media_folder: "public/uploads"
public_folder: "uploads"

collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "src/test-data.json"
      fields:
        - {label: Main title, name: maintitle, widget: string}
        - {label: Main label, name: mainlabel, widget: markdown}
        - {label: Banner video, name: bannerVideo, widget: file, required: true}
        - {label: brand Title, name: brandTitle, widget: markdown}
        - {label: brand Text, name: brandText, widget: markdown}
        - {label: brand Photo, name: brandPhoto, widget: image}

# collections:
#   - label: "Pages"
#     name: "pages"
#     folder: "_datas" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collections
#     slug: "{{YYYY-MM-DD-title.md}}" # Filename template, e.g., YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#         - {label: Main title, name: maintitle, widget: string}
#         - {label: Main label, name: mainlabel, widget: markdown}
#         - {label: Banner video, name: bannerVideo, widget: file, required: true}
#         - {label: brand Title, name: brandTitle, widget: markdown}
#         - {label: brand Text, name: brandText, widget: markdown}
#         - {label: brand Photo, name: brandPhoto, widget: image}